### ISSUE TITLE
Adding correct settings results in a spinner

### ISSUE THREAD

**Issue by jjbrunton** [christophercatt/listarr#1]
I've filled in:

Sonarr Url (tried both internal and reverse proxy domain)
Sonarr API key (double checked this)
Trakt Client ID

When doing test connection or save, I get a spinner.

I'm running Sonarr v3 if that makes a difference?

**Comment by jjbrunton** [comment]
Ok, looking into this, it actually filled 9GB of RAM across both Sonarr and Listarr so I've stopped it for now as it brought my server to its knees!

**Comment by christophercatt** [comment]
Hi, I've just tried this on a Sonarr V3 instance and I could not replicate this issue as of current. Please could you you answer the following questions to help me to try and fix this for you:

- What installation method/system are you using (Docker image, install on Unix/Windows)
- If on Windows/Unix (non Docker), does the following folder get generated 'listarr/server/config'
- Do you append 'http://' or 'https://' to the beginning of your Sonarr URL within the settings menu
- Is your Sonarr instance behind a authentication system (other than Sonarr's own login forms)
- Lastly, is there anything within the logs of the program following the line 'server started on port 5000'

The application only pulls the existing series from Sonarr after the time set within the settings page, when it attempts to loop throughout added lists and add them to Sonarr, so if there is a size issue it should only occur then instead of when testing settings. 

Many thanks

**Comment by jjbrunton** [comment]
Hiya @christophercatt 

- I'm using Docker running on a Ubuntu host
- I've tried both the internal docker hostname of Sonarr and the reverse proxy address
- There's no additional authentication other than Sonarr itself
- I didn't notice anything in the logs other than the initial node startup information

Basically I'd test the settings to which it would OK them, I'd then press save and a spinner would appear. At this point the spinner would stay and if I monitored my system with htop/top the memory of the Sonarr docker instance would just climb and climb until it began swapping and bringing the system to a crawl.

**Comment by christophercatt** [comment]
@jjbrunton 

Thank you for that information, I've just added a new Docker tag with some additional debugging info inside of it for me to look at to find the source of this problem. If you could try using the `ccatt601/listarr:bugfix-v1.0.1-alpha` image and reply with the contents of the logs after running that please. Also, could you include the browser console logs as well, as I've added some debugging info in the client side code too. Please allow the image to run for as long as you can (without it crippling your server of course)

**Comment by christophercatt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bugfix Update v1.0.1-alpha](https://trello.com/c/iqFKNFlX/51-bugfix-update-v101-alpha)

**Comment by christophercatt** [comment]
I have closed this issue for now as I have not heard a response and have implemented a new version which  *should* fix this issue. If this issue persists, then please reopen and I will gladly assist
