### ISSUE TITLE
[bug?/feature request] Doesn't add shows from a private trakt list

### ISSUE THREAD

**Issue by JourneyOver** [christophercatt/listarr#4]
So I have a few private trakt lists (they are my own lists but I have them set to private for reasons) that I use for sonarr, thing is; is that it doesn't seem to see/add any shows from a private list. I ran it on a test list with 1 show in it first having it set to private, waited the allotted time I had set and it never added the show to sonarr, instead it would just continue spitting out:
```
--- Adding Lists ---
--- Sent Lists To Sonarr ---
```
whenever it would do anything.

Then I went and switched the test list to public instead and waited the allotted time again and this time it added the show just fine.
```
--- Adding Lists ---
Attempting To Add 1 Shows
--- Sent Lists To Sonarr ---
```

So I guess what I'm trying to figure out is if this is a bug or not, and if it's not can you please add a way so that private lists will work.

**Comment by christophercatt** [comment]
Hi @JourneyOver 

Currently private lists are not supported, as they require authentication tokens generated from Trakt third party sign-on. This has not been implemented yet due to the extra security considerations that should (must) be first implemented. I will add it to the feature requests board and close this issue for now, however this feature may take longer to get to as I have an existing backlog to work through first.

**Comment by christophercatt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Private Lists](https://trello.com/c/R9bLcP5L/59-private-lists)
